### ISSUE TITLE
arrayfile missing?

### ISSUE THREAD

**Issue by nypdmax** [ririhedou/systemCallAnomalyDetectionLSTM#1]
Hello @ririhedou,
I'm trying to run your code but  

`arrayfile = "/Users/ketian/Desktop/array_test.pickle"  `
`array = io_helper.loadfrompickle(arrayfile)`
 in preprecess.py is causing troubles.
Can you include the `/Users/ketian/Desktop/array_test.pickle` in your repo?

Thanks,
Max

**Comment by warvyvr** [comment]
please run `inputdata.py` to generate that file.
